 |

            There are two steps involved in the basic workflow for accepting a deal proposal as-is:

                - List available deals, 
                - Purchase a selected deal.


            #### 2.1.1 List available deals

            To list all available deals, Send a GET request to the /deals/proposals endpoint:

            ```
            $ curl -X GET \
                -H 'IXM-UserID: 1234' \
                -H 'IXM-AccessToken: oFimaL5gCz9yJq2IKenrev2pclk5ul7P' \
                https://market.indexexchange.com/api/v1/deals/proposals
            ```

            In response, a list of available deal proposals is returned. Responses may differ based on:

                - Filters. A response may optionally be filtered by any of the available filters described in the deal proposals route.
                - Pagination maximums. The pagination object specifies the requested maximum objects and the current page offset. The number of available deals returned is limited to the pagination maximum.

            ```
            {
                "code": 200,
                "message": "Is your daddy a dealer, cause you're dope to me?"
                "data": [
                    {
                        "proposal_id": 999,
                        "owner": {
                            "owner_id": 123,
                            "contact": {
                                "title": "Captain",
                                "name": "Jimdex Exchange",
                                "email": "jimdex.exchange@indexexchange.com",
                                "phone": "666 666 6665"
                            }
                        },
                        "inventory": [4321, 9876],
                        "name": "Superfab Ultradeal",
                        "description": "DWI https://media.giphy.com/media/GODSCQebffJzW/giphy.gif",
                        "status": "active",
                        "start_date": "2017-09-09",
                        "end_date": "2017-10-10",
                        "price": 1.99,
                        "impressions": 8,
                        "budget": 9999999.99,
                        "currency": "USD",
                        "auction_type": "first",
                        "terms": "Hom ngav taq yas cha'dich 'usgheb abigaile adin billy kristina lea nomi sandra stella susana tindra choronzon corson eurynomos kali mammon mephistopheles neqa'el vapula ɔouʌɐllıs ıuʇǝƃǝɹ ɯɐƃuıs sɐƃıʇʇıs nlʇɹıɔıǝs",
                        "created_at": "2017-04-04T04:00:00Z",
                        "modified_at": "2017-04-14T14:00:00Z"
                    },
                    {
                        "proposal_id": 888,
                        "owner": {
                            "owner_id": 123,
                            "contact": {
                                "title": "Bossperson",
                                "name": "Grunt McSlab",
                                "email": "gruntslab@wemakenews4u.com",
                                "phone": "666 666 6665"
                            }
                        },
                        "inventory": [4321, 9876],
                        "name": "Superfab Ultradeal",
                        "description": "DWI https://media.giphy.com/media/GODSCQebffJzW/giphy.gif",
                        "status": "active",
                        "start_date": "2017-09-09",
                        "end_date": "2017-10-10",
                        "price": 1.99,
                        "impressions": 8,
                        "budget": 999999,
                        "currency": "USD",
                        "auction_type": "first",
                        "terms": "Hom ngav taq yas cha'dich 'usgheb abigaile adin billy kristina lea nomi sandra stella susana tindra choronzon corson eurynomos kali mammon mephistopheles neqa'el vapula ɔouʌɐllıs ıuʇǝƃǝɹ ɯɐƃuıs sɐƃıʇʇıs nlʇɹıɔıǝs",
                        "created_at": "2017-04-04T04:00:00Z",
                        "modified_at": "2017-04-14T14:00:00Z"
                    }                

                ],
                "pagination": {
                    "page": 2,
                    "limit": 250,
                    "next_page_url": "https://market.indexexchange.com/api/v1/deals/proposals/?page=3&limit=250",
                    "prev_page_url": "https://market.indexexchange.com/api/v1/deals/proposals/?page=1&limit=250"
                }
            }
            ```

            #### 2.1.2 Accept the deal

            Our simplified example illustrates two proposals available for purchase: 1“Great deal”1 and 1“Superfab Ultradeal”1. Let’s assume 1“Superfab Ultradeal”1 is perfect and we agree with all terms in the proposal. 
            We can accept this deal as-is by sending a PUT request to /deals/active. The body of the request is a JSON object containing the proposal ID:

            ```
            $ curl -X PUT \
                -H 'IXM-UserID: 1234' \
                -H 'IXM-AccessToken: oFimaL5gCz9yJq2IKenrev2pclk5ul7P' \
                -H 'Content-Type: application/json' \
                -d '{ "proposalID": 888 }' \
                https://market.indexexchange.com/api/v1/deals/active
            ```

            We now have an active deal named “Superfab Ultradeal” which is available for bidding starting on September 9th, 2017. 

            In response, we receive a deal object and a unique external_id which may be used as a reference or identifier in other systems:

            ```
            {
                "code": 200,
                "message": "Deal with it",
                "data": [
                    {
                        "proposal": {
                            "id": 888,
                            "name": "Superfab Ultradeal",
                            "description": "DWI https://media.giphy.com/media/GODSCQebffJzW/giphy.gif",
                            "currency": "USD"
                        },
                        "partner": {
                            "id": 123,
                            "partner_contact": {
                                "title": "Bossperson",
                                "name": "Grunt McSlab",
                                "email": "gruntslab@wemakenews4u.com",
                                "phone": "666 666 6665"
                            }
                        },
                        "external_id": "DEAL-4-U-BB",
                        "inventory": [4321, 9876],
                        "status": "active",
                        "start_date": "2017-09-09",
                        "end_date": "2017-10-10",
                        "price": 1.99,
                        "impressions": 8,
                        "budget": 999999,
                        "auction_type": "first",
                        "terms": "Hom ngav taq yas cha'dich 'usgheb abigaile adin billy kristina lea nomi sandra stella susana tindra choronzon corson eurynomos kali mammon mephistopheles neqa'el vapula ɔouʌɐllıs ıuʇǝƃǝɹ ɯɐƃuıs sɐƃıʇʇıs nlʇɹıɔıǝs",
                        "dsp_id": 6,
                        "created_at": "2017-04-04T04:00:00Z",
                        "modified_at": "2017-04-14T14:00:00Z"
                    }   
                ]
            }
            ```
