 |

            This workflow illustrates the creation of a proposal. A proposal may be created by any user of IX Market and viewed on the market by all parties.

            In our example, a publisher creates a proposal which attracts the interest of two buyers. One buyer is interested in immediately accepting the proposal as-is; the other buyer wishes to negotiate the terms. This process spans three stages:

                1. Create a proposal
                2. Receive responses from buyers
                3. Respond to results


            #### 2.4.1 Create a proposal

            To create a proposal, a request is sent to the PUT `/deals/proposals` route. This proposal is available on the open IX market because the `partners` property is omitted. If the publisher had included `partners`, this would be a targeted proposal. 

            The publisher also includes specific [sites]( link ) and/or [sections]( link ) they own as part of the proposal.

            Contact information is sourced by default from the publisher’s account but can be overridden via inclusion of the `contact` field.

            ```
            $ curl -X PUT \
                -H 'IXM-UserID: 123' \
                -H 'IXM-AccessToken: oFimaL5gCz9yJq2IKenrev2pclk5ul7P' \
                -d '{
                        "inventory": [4321, 9876],
                        "name": "Superfab Ultradeal",
                        "description": "DWI https://media.giphy.com/media/GODSCQebffJzW/giphy.gif",
                        "start_date": "2017-09-09",
                        "end_date": "2017-10-10",
                        "price": 1.99,
                        "impressions": 8,
                        "budget": 999999,
                        "currency": "USD",
                        "auction_type": "first",
                        "contact": {
                            "title": "Lord",
                            "name": "Humungus",
                            "email": "ayatollah@rockandrollah.com",
                            "phone": "999 999 9998"
                        },
                        "terms": "Hom ngav taq yas cha'dich 'usgheb abigaile adin billy kristina lea nomi sandra stella susana tindra choronzon corson eurynomos kali mammon mephistopheles neqa'el vapula ɔouʌɐllıs ıuʇǝƃǝɹ ɯɐƃuıs sɐƃıʇʇıs nlʇɹıɔıǝs"
                    }' \
                https://market.indexexchange.com/api/v1/deals/proposals
            ```

            The successful creation of a proposal is confirmed via the details of the new proposal, including the assignment of a `proposal_id`. 

            In our example, the proposal above was assigned a `proposal_id` of `888`.

            #### 2.4.2 Receive responses

            Buyers can now view this proposal by sending a GET request to the `/deals/proposals` route. A buyer may accept it immediately or to submit a counter-offer with amended deal terms. 

            In our example, the first buyer immediately accepts the proposal as-is:
            
            ```
             $ curl -X PUT \
                -H 'IXM-UserID: 1234' \
                -H 'IXM-AccessToken: oFimaL5gCz9yJq2IKenrev2pclk5ul7P' \
                -d '{ "proposal_id": 888 }' \
                https://market.indexexchange.com/api/v1/deals/active
            ```

            The second buyer wishes to negotiate the terms and so submits a counter-offer: 
            
            ```
             $ curl -X PUT \
                -H 'IXM-UserID: 456' \
                -H 'IXM-AccessToken: oFimaL5gCz9yJq2IKenrev2pclk5ul7P' \
                -d '{ "proposal_id": 888, "partner_id": 123, "price": "2.99" "terms": "Try harder bro" }' \
                https://market.indexexchange.com/api/v1/deals/negotiations
            ```

            #### 2.4.3 Respond to results

            The publisher is notified of both responses. The first response results in an active deal, which is seen in the GET `/deals/active` route. 

            The second response results in a counter-offer, available in Negotiated Deals via the GET `/deals/negotiations` route. This publisher is unwilling to consider any terms other than those specified in their proposal and therefore immediately rejects the counter-offer by sending a PUT request to `/deals/negotiations` as seen below: 

            ```
             $ curl -X PUT \
                -H 'IXM-UserID: 123' \
                -H 'IXM-AccessToken: oFimaL5gCz9yJq2IKenrev2pclk5ul7P' \
                -d '{ "proposal_id": 888, partner_id: 456, "response": "reject" }' \
                https://market.indexexchange.com/api/v1/deals/negotiations
            ```

            This proposal is no longer available to the second buyer but remains on the open market until the end date passes or the publisher closes it.