version: '2'

networks:
  atwater:
    external: true
  internal:
    external: true

services:
  atw-api:
    container_name: "atw-api"
    restart: "no"
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile
      args:
        ENVIRONMENT: $ENVIRONMENT
        DATE: $DATE
        GIT_COMMIT: $GIT_COMMIT
    image: ir.indexexchange.com:5000/atw-api$VERSION
    logging:
      driver: "journald"
      options:
        tag: "atwater.api"
    networks:
      - atwater
    entrypoint: sh /src/docker/scripts/entrypoint.sh $ENVIRONMENT
    volumes:
      - "/src/atwater.git/api/:/src/:ro"
  atw-nginx:
    container_name: "atw-nginx"
    restart: "no"
    build:
      context: ./nginx
      dockerfile: ./docker/Dockerfile
      args:
        ENVIRONMENT: $ENVIRONMENT
        DATE: $DATE
        GIT_COMMIT: $GIT_COMMIT
    image: ir.indexexchange.com:5000/atw-nginx$VERSION
    logging:
      driver: "journald"
      options:
        tag: "atwater.nginx"
    networks:
      - atwater
      - internal
    entrypoint: sh /src/docker/scripts/entrypoint.sh $ENVIRONMENT
    volumes:
      - "/src/atwater.git/nginx/:/src/:ro"
    ports:
      - "443:443"