version: '2'

networks:
  atwater:
    external: true
  internal:
    external: true

services:
  atw-api:
    container_name: "atw-api"
    restart: "no"
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile
    image: atw-api:dev
    networks:
      - atwater
    entrypoint: "sh /src/docker/scripts/entrypoint.sh"
    volumes:
      - "/src/atwater.git/api/:/src/:ro"
  atw-nginx:
    container_name: "atw-nginx"
    restart: "no"
    build:
      context: ./nginx
      dockerfile: ./docker/Dockerfile
    image: atw-nginx:dev
    networks:
      - atwater
      - internal
    entrypoint: "sh /src/docker/scripts/entrypoint.sh"
    volumes:
      - "/src/atwater.git/nginx/:/src/:ro"
    ports:
      - "443:443"