version: '2'

networks:
  atwater:
    external: true

services:
  atw-api:
    extends:
      file: "api/docker/compose/$IMAGE_TYPE.yml"
      service: "atw-api"
  atw-nginx:
    extends:
      file: "nginx/docker/compose/$IMAGE_TYPE.yml"
      service: "atw-nginx"