version: '2'

networks:
  atwater:
    external: true

services:
  atw-api:
    container_name: "atw-api"
    restart: "always"
    image: pr.indexexchange.com:5000/atw-api$APIVERSION
    logging:
      driver: "syslog"
      options:
        tag: "atwater.api"
    networks:
      - atwater
    volumes:
      - "/services/ixm/api/.env:/opt/atw-api/.env:ro"
  atw-nginx:
    container_name: "atw-nginx"
    restart: "always"
    image: pr.indexexchange.com:5000/atw-nginx$NGINXVERSION
    logging:
      driver: "syslog"
      options:
        tag: "atwater.nginx"
    networks:
      - atwater
    ports:
      - "443:443"
    volumes:
      - "/services/ixm/nginx/ssl:/etc/nginx/ssl:ro"