version: '2'

networks:
  atwater:
    external: true

services:
  atw-api:
    container_name: "atw-api"
    restart: "always"
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile
      args:
        ENVIRONMENT: production
        DATE: $ATW_DATE
        GIT_COMMIT: $ATW_GIT_COMMIT
        DOCKERFILE_URL: $ATW_API_DOCKERFILE_URL
    image: pr.indexexchange.com:5000/atw-api$ATW_APIVER
    logging:
      driver: "syslog"
      options:
        tag: "atwater.api"
    networks:
      - atwater
    volumes:
      - "/services/ixm/atw-api/.env:/opt/atwater/api/.env:ro"
      - "/var/log/ixm/atw-api/:/opt/atwater/api/logs/"
  atw-nginx:
    container_name: "atw-nginx"
    restart: "always"
    build:
      context: ./nginx
      dockerfile: ./docker/Dockerfile
      args:
        ENVIRONMENT: production
        DATE: $ATW_DATE
        GIT_COMMIT: $ATW_GIT_COMMIT
        DOCKERFILE_URL: $ATW_NGINX_DOCKERFILE_URL
    image: pr.indexexchange.com:5000/atw-nginx$ATW_NGINXVER
    logging:
      driver: "syslog"
      options:
        tag: "atwater.nginx"
    networks:
      - atwater
    ports:
      - "4433:443"
    volumes:
      - "/services/ixm/atw-nginx/ssl:/etc/nginx/ssl:ro"