version: '2'

networks:
    atwater:
        external: true
    internal:
        external: true

services:
    atw-api:
        container_name: "atw-api"
        restart: "no"
        build:
            context: ./api
            dockerfile: ./docker/Dockerfile
        image: ir.indexexchange.com:5000/atw-api$ATW_APIVER
        entrypoint: "sh /src/docker/entrypoint-api.sh"
        logging:
            driver: "journald"
            options:
                tag: "atwater.api"
        networks:
            atwater:
                aliases:
                    - api.atwater
        volumes:
            - "./api/:/src/"
            - "/var/log/ixm/atw-api/:/opt/atwater/api/logs/"
    atw-nginx:
        container_name: "atw-nginx"
        hostname: "market.indexexchange.com"
        restart: "no"
        build:
            context: ./nginx
            dockerfile: ./docker/Dockerfile
        image: ir.indexexchange.com:5000/atw-nginx$ATW_NGINXVER
        entrypoint: "sh /src/docker/entrypoint-nginx.sh"
        logging:
            driver: "journald"
            options:
                tag: "atwater.nginx"
        networks:
            atwater:
            internal:
                aliases:
                    - market.indexexchange.com
        volumes:
            - "./nginx/:/src/:ro"
        depends_on:
            - atw-api
    workstation-proxy:
        extends:
            file: ../docker.git/servers/workstation.yaml
            service: workstation-proxy
        depends_on:
            - atw-nginx
