#%RAML 1.0 

displayName: GET Deal Negotiations 200 "No Content" Response
description: This response will be sent if no deals in negotiation can be found for the current user.
value:
	code: 200
	message: No negotiations are currently available. Come back later or try a different offset!
	data: []
