#%RAML 1.0 

displayName: PUT /deals/negotiations Rejection Request
description: This request will reject the current negotiation offer. The negotiation will be closed, but new negotiations can be started on the same proposal. Closed negotiations will be available to view until new negotiation is started.
value:
	proposal_id: 969
	partner_id: 696
	response: "reject"
