#%RAML 1.0 

displayName: PUT /deals/negotiations Counter Offer Request
description: This request will send a counter-offer on the specified deal in negotiation, requesting a different price and updating the terms & conditions.
value:
	proposal_id: 969
	partner_id: 696
	price: 1.23
	terms: "The plan was, we drink until the pain's over. But what's worse? The pain, or the hangover?"
	