#%RAML 1.0 DataType
Duck:
    type: object
    additionalProperties: false
    properties:
        attack:
            type: string
            default: meow
            required: false
        defense:
            type: number
            default: 3
            required: true
