#%RAML 1.0 DataType
Turtle:
    type: Pet
    properties:
        shellStrength:
            type: number
            default: 0.01596
            required: true
        eatingPower?:
            type: integer
            default: 4