#%RAML 1.0 DataType

type: object
description: An object containing contact information, which may be associated with deals, available deal sections or profiles.
properties:
    email:
        type: string
        required: true
        displayName: Contact Email
        description: The contact's email address.
    name:
        type: string
        required: true
        displayName: Contact Name
        description: The contact's name.
    phone:
        type: string
        required: true
        displayName: Contact Phone Number
        description: The contact's phone number.
    title:
        type: string
        required: false
        displayName: Job Title
        description: The contact's job title or position.
example: |
    {
        "title": "Captain",
        "name": "Jimdex Exchange",
        "email": "jimdex.exchange@indexexchange.com",
        "phone": "666 765 4321"
    }