#%RAML 1.0 DataType

type: object
description: An object describing the request body needed to create a new proposal
properties:
    auction_type:
        type: string
        required: true
        displayName: Auction Type,
        description: The auction type - 'first' = First Price, 'second' = Second Price, 'fixed' = Fixed Rate.
        enum: ['first','second','fixed']
    budget:
        type: integer
        required: false
        displayName: Budget
        description: The projected amount to be spent by the buyer.
        minimum: 1
        maximum: 16777215
    contact:
        type: object
        required: false
        description: An object containing contact information, which may be associated with deals, available deal sections or profiles.
        properties:
            email:
                type: string
                required: true
                displayName: Contact Email
                description: The contact's email address.
            name:
                type: string
                required: true
                displayName: Contact Name
                description: The contact's name.
            phone:
                type: string
                required: true
                displayName: Contact Phone Number
                description: The contact's phone number.
            title:
                type: string
                required: false
                displayName: Job Title
                description: The contact's job title or position.
    description:
        type: string
        required: false
        displayName: Description
        description: A description of the deal.
        maxLength: 255
    end_date:
        type: date-only
        required: false
        displayName: End Date
        description: The end date of the deal, if applicable. RFC3339 "full-date" format. If omitted, deal does not expire.
        example: 2017-10-10
    impressions:
        type: integer
        required: false
        displayName: Impressions
        description: The projected amount of impressions for the deal.
        example: USD
        minimum: 0
        maximum: 16777215
    inventory:
        type: array
        required: false
        minItems: 1
        items:
            type: integer
            minimum: 1
            maximum: 16777215
        displayName: Inventory Section Id(s)
        description: An array of Inventory Section IDs, indicating which sections will be active in this deal. (See "Section" type.)
    name:
        type: string
        required: true
        displayName: Name
        description: Name of the deal.
        minLength: 1
        maxLength: 255
    partners:
        type: array
        required: false
        minItems: 1
        items:
            type: integer
            minimum: 1
            maximum: 16777215
        displayName: Targeted Partners
        description: Optional partner targeting. If this is included, the proposal will not be visible on the open market: only targeted partners will be able to see it. Partners will be notified, and will be able to accept, reject, or negotiate on the proposed deal.
    price:
        type: number
        required: true
        displayName: Deal Price
        description: The deal price. This is the floor price for "First Price" or "Second Price" deals, or the fixed price for "Fixed Rate" deals. (See auction_type.) Dollars with two decimal cents.
        example: 1.99
        minimum: 0.01
        maximum: 655.35
    start_date:
        type: date-only
        required: false
        displayName: Start Date
        description: The start date of the deal, if applicable. RFC3339 "full-date" format. If ommitted, deal is set to start immediately on acceptance.
        example: 2017-09-09
    terms:
        type: string
        required: false
        displayName: Terms & Conditions
        description: The terms & conditions for the deal - extra information describing the deal.
        minLength: 1
        maxLength: 65535
example: |
    {
        "partners": [123, 456],
        "inventory": [4321, 9876],
        "partners": [123, 456],
        "name": "Superfab Ultradeal",
        "description": "DWI https://media.giphy.com/media/GODSCQebffJzW/giphy.gif",
        "start_date": "2017-09-09",
        "end_date": "2017-10-10",
        "price": 1.99,
        "impressions": 8,
        "budget": 9999999,
        "auction_type": "first",
        "contact": {
            "title": "Captain",
            "name": "Jimdex Exchange",
            "email": "jimdex.exchange@indexexchange.com",
            "phone": "666 666 6665"
        },
        "terms": "Hom ngav taq yas cha'dich 'usgheb abigaile adin billy kristina lea nomi sandra stella susana tindra choronzon corson eurynomos kali mammon mephistopheles neqa'el vapula ɔouʌɐllıs ıuʇǝƃǝɹ ɯɐƃuıs sɐƃıʇʇıs nlʇɹıɔıǝs"
    }