#%RAML 1.0 DataType

type: object
description: An object describing a deal available to buy on a deal section
properties:
    auction_type:
        type: string
        required: true
        displayName: Auction Type
        description: The auction type - 'first' = First Price, 'second' = Second Price, 'fixed' = Fixed Rate.
        enum: ['first','second','fixed']
    budget:
        type: integer
        required: false
        displayName: Budget
        description: The projected amount to be spent by the buyer.
    created_at:
        type: datetime
        required: true
        displayName: Created At
        description: The timestamp the deal was created at. RFC3339 format, UTC.
    currency:
        type: string
        required: true
        displayName: Currency
        description: Three-letter currency code for the deal.
        example: USD
    description:
        type: string
        required: false
        displayName: Description
        description: A description of the deal.
        maxLength: 255
    end_date:
        type: date-only
        required: false # should we omit date for 'ongoing'? Or?
        displayName: End Date
        description: The end date of the deal, if applicable. RFC3339 "full-date" format. If omitted, deal does not expire.
        example: 2017-10-10
    impressions:
        type: integer
        required: false
        displayName: Impressions
        description: The projected amount of impressions for the package.
        minimum: 0
        maximum: 16777215
    inventory:
        type: Section[]
        required: true
        displayName: Inventory Sections
        description: An array of Inventory Sections, indicating which sections will be active in this deal.
    modified_at:
        type: datetime
        required: true
        displayName: Modified At
        description: The timestamp the deal was last modified at. RFC3339 format, UTC.
    name:
        type: string
        required: true
        displayName: Name
        description: Name of the deal.
        maxLength: 255
    owner:
        type: Owner
        required: true
        displayName: owner
        description: Information about the owner of this proposal.
    partners:
        type: integer[]
        required: false
        displayName: Partners
        description: An array of Partner IDs, indicating which users are targeted by this proposal. If empty or not provided, this proposal is open to everyone.
    price:
        type: number
        required: true
        displayName: Deal Price
        description: The deal price. This is the floor price for "First Price" or "Second Price" deals, or the fixed price for "Fixed Rate" deals. (See auction_type.) Dollars with two decimal cents.
        example: 1.99
        minimum: 0.01
        maximum: 655.35
    proposal_id:
        type: integer
        required: true
        displayName: Proposal ID
        description: The unique identifier for the proposal.
    start_date:
        type: date-only
        required: false
        displayName: Start Date
        description: The start date of the deal, if applicable. RFC3339 "full-date" format. If ommitted, deal is set to start immediately on acceptance.
        example: 2017-09-09
    status:
        type: string
        required: true
        displayName: Status
        description: The deal's current status.
        enum: ["active", "inactive"]
    terms:
        type: string
        required: false
        displayName: Terms & Conditions
        description: The terms & conditions for the deal - extra information describing the deal.
        maxLength: 65535
example: |
    {
        "proposal_id": 999,
        "inventory": [4321, 9876],
        "partners": [123, 456],
        "name": "Superfab Ultradeal",
        "description": "DWI https://media.giphy.com/media/GODSCQebffJzW/giphy.gif",
        "status": "active",
        "start_date": "2017-09-09",
        "end_date": "2017-10-10",
        "price": 1.99,
        "impressions": 8,
        "budget": 9999999,
        "currency": "USD",
        "auction_type": "first",
        "owner": {
            "owner_id": 123,
            "contact": {
                "title": "Captain",
                "name": "Jimdex Exchange",
                "email": "jimdex.exchange@indexexchange.com",
                "phone": "666 666 6665"
            }
        },
        "terms": "Hom ngav taq yas cha'dich 'usgheb abigaile adin billy kristina lea nomi sandra stella susana tindra choronzon corson eurynomos kali mammon mephistopheles neqa'el vapula ɔouʌɐllıs ıuʇǝƃǝɹ ɯɐƃuıs sɐƃıʇʇıs nlʇɹıɔıǝs",
        "created_at": "2017-04-04T04:00:00Z",
        "modified_at": "2017-04-14T14:00:00Z"
    }