#%RAML 1.0 DataType

type: object
description: An object describing an active deal in the system
properties:
    id:
        type: integer
        required: true
        displayName: Deal ID
        description: A unique identifier for the active deal
    publisher_id:
        type: integer
        required: true
        displayName: Publisher ID
        description: ID of the publisher involved in the deal
    dsp_id:
        type: integer
        required: true
        displayName: DSP ID
        description: ID of the DSP involved in the deal
    name:
        type: string
        required: true
        displayName: Name
        description: Name of the deal
    price:
        type:
        required:
        displayName: 
        description:
    external_id:
        type:
        required:
        displayName:
        description:
    sections:
        type:
        required:
        displayName:
        description:
    auction_type:
        type:
        required:
        displayName:
        description:
    status:
        type:
        required:
        displayName:
        description:
    start_date:
        type:
        required:
        displayName:
        description:
    end_date:
        type:
        required:
        displayName:
        description:
example: |
    {
        "id":
        "publisher_id":
        "dsp_id":
        "name":
        "price":
        "external_id":
        "section":
        "auction_type":
        "status":
        "start_date":
        "end_date":
    }
