#%RAML 1.0 DataType

type: object
description: An object defining the current state of pagination; current page and limit.  
properties:
    limit:
        type: integer
        required: true
        displayName: Limit
        description: The page size of each page returned.
        minimum: 1
        maximum: 250
    next_page_url:
        type: string
        required: true
        displayName: Next Page URL 
        description: A link to the next page of results with same limit. If the current page contains the last available result, the next page URL will return an empty set.
    page:
        type: integer
        required: true
        displayName: Page
        description: The current page number of the data returned. Dependent on limit.
        minimum: 1
        maximum: 4294967295
    prev_page_url:
        type: string
        required: true  
        displayName: Previous Page URL 
        description: A link to the previous page of results with same limit. Returned as empty string if current page is the first page.    
example: |
    {
        "page": 2,
        "limit": 250,
        "next_page_url": "https://market.indexexchange.com/api/v1/deals/negotiations/?page=3&limit=250",
        "prev_page_url": "https://market.indexexchange.com/api/v1/deals/negotiations/?page=1&limit=250"
    }