#%RAML 1.0 DataType

type: object
description: An object describing the request body needed to create a new proposal
    auction_type:
        type: string
        required: true
        displayName: Auction Type,
        description: The auction type - 'first' = First Price, 'second' = Second Price, 'fixed' = Fixed Rate.
        enum: ['first','second','fixed']
    budget:
        type: integer
        required: false
        displayName: Budget
        description: The projected amount to be spent by the buyer.
    contact:
        type: Contact
        required: false
        displayName: Contact Information    
        description: The primary contact information for the proposal's owner. Overrides default user contact info if provided.
    currency:
        type: string
        required: true
        displayName: Currency
        description: Three-letter currency code for the deal.
    description:
        type: string
        required: false
        displayName: Description
        description: A description of the deal.
        maxLength: 255
    end_date:
        type: date-only
        required: false
        displayName: End Date
        description: The end date of the deal, if applicable. RFC3339 "full-date" format. If omitted, deal does not expire.
        example: 2016-10-10
    impressions:
        type: integer
        required: false
        displayName: Impressions
        description: The projected amount of impressions for the package.
        example: USD
        minimum: 0
        maximum: 16777215
    inventory:
        type: integer[]
        required: true
        displayName: Inventory Section Id(s)
        description: An array of Inventory Section IDs, indicating which sections will be active in this deal.
    name:
        type: string
        required: true
        displayName: Name
        description: Name of the deal.
        maxLength: 255
    partners:
        type: integer[]
        required: false
        displayName: Partners
        description: An array of Partner IDs, indicating which users are targeted by this proposal. If empty or not provided, this proposal is open to everyone.
    price:
        type: number
        required: true
        displayName: Deal Price
        description: The deal price. This is the floor price for "First Price" or "Second Price" deals, or the fixed price for "Fixed Rate" deals. (See auction_type.) Dollars with two decimal cents.
        example: 1.99
        minimum: 0.01
        maximum: 655.35
    start_date:
        type: date-only
        required: false
        displayName: Start Date
        description: The start date of the deal, if applicable. RFC3339 "full-date" format. If ommitted, deal is set to start immediately on acceptance.
        example: 2016-09-09
    terms:
        type: string
        required: false
        displayName: Terms & Conditions
        description: The terms & conditions for the deal - extra information describing the deal.
        maxLength: 65535
example: |
    {
        "inventory": [4321, 9876],
        "partners": [123, 456],
        "name": "Superfab Ultradeal",
        "description": "DWI https://media.giphy.com/media/GODSCQebffJzW/giphy.gif",
        "start_date": "2016-09-09",
        "end_date": "2016-10-10",
        "price": 1.99,
        "impressions": 8,
        "budget": 9999999,
        "currency": "USD",
        "auction_type": "first",
        "contact": {
            "title": "Captain",
            "name": "Jimdex Exchange",
            "email": "jimdex.exchange@indexexchange.com",
            "phone": "666 666 6665"
        },
        "terms": "Hom ngav taq yas cha'dich 'usgheb abigaile adin billy kristina lea nomi sandra stella susana tindra choronzon corson eurynomos kali mammon mephistopheles neqa'el vapula ɔouʌɐllıs ıuʇǝƃǝɹ ɯɐƃuıs sɐƃıʇʇıs nlʇɹıɔıǝs"
    }