#%RAML 1.0 DataType
Pagination:
    type: object
    properties:
        limit:
            type: integer
            required: false
            minimum: 1
            maximum: 250
            default: 250
        page:
            type: integer
            required: false
            minimum: 1
            maximum: 4294967295
            default: 1