# Authentication Configuration

# The header which contains the access token
tokenHeader: IXM-AccessToken

# The header containig the user id
userHeader: IXM-UserID

# A switch for allowing public use of API
public: false

# The JWT secret.
jwtSecret: qwerty

# Ignore auth tokens. Setting this to true allows you to pass { "userID": userID, "userType": userType } in the token header.
ignoreTokens: false