# Authentication Configuration

# Usertype names of usertypes allowed to access IXM
allowedUserTypes:
    - IXMB
    - IXMP

# The header which contains the access token
tokenHeader: IXM-AccessToken

# The header containig the user id
userHeader: IXM-UserID

# A switch for allowing public use of API
public: true
