# Authentication Configuration

# The server information for token verification
httpOptions:
    hostname: auth.indexexchange.com
    path: /verify
    method: POST

# Usertype names of usertypes allowed to access IXM
allowedUserTypes:
    - IXMB
    - IXMP

# The header which contains the access token
header: X-IXM-BuyerId

# A switch for allowing public use of API
public: true