# Standardized Error Messages

# US English
en-US:

    # 200 Status Code Messages
    200: Ok.
    200_NO_CONTENT: No content.
    200_NO_PROPOSALS: No deals are currently available. Come check again soon!
    200_NO_DEALS: You don't seem to have any active deals at the moment. Sorry, eh!
    200_NO_NEGOTIATIONS: You have no negotiations you agreeable bastard.
    
    # 400 Status Code Messages
    400: Malformed request.
    
    # 401 Status Code Messages
    401: Unauthorized.
    401_INVALID_HEADER: Authentication header is invalid.
    401_NO_HEADER: Authentication header not provided.
    401_NOT_IXMBUYER: 'Provided user ID is not an Index Market Buyer. If you would like access, please contact your.mom@indexexchange.com'
    401_NOT_ACTIVE: 'Provided user ID is not currently active. If you would like access, please contact jeff.bezos@indexexchange.com'
    401_PRIVATE: 'The Index Market API is not open to the public. If you would like access, please contact larry.page@indexexchange.com'

    # 403 Status Code Messages
    403: Forbidden.
    403_NOT_FORSALE: Proposal is not available for purchase.
    403_PROPOSAL_BOUGHT: Proposal has already been accepted.
    403_PROPOSAL_IN_NEGOTIATION: Proposal is in negotiation.
    403_BAD_PROPOSAL: The proposal does not match the provided partner.
    403_CANNOT_START_NEGOTIATION: Cannot start a negotiation on your own proposal.
    403_OTHER_REJECTED: The partner rejected this negotiation, the proposal cannot be bought as is.
    403_OUT_OF_TURN: The partner did not reply to your previous offer.
    403_NO_CHANGE: At least one negotiation field must be different than current offer.

    # 404 Status Code Messages
    404: Not found.
    404_PROPOSAL_NOT_FOUND: Proposal not found.

    # 500 Status Code Messages
    500: Internal server error.
