# Standardized Error Messages

# US English
en-US:

    # 200 Status Code Messages
    200: Ok.
    200_NO_CONTENT: No content.
    200_NO_PROPOSALS: No deals are currently available. Come check again soon!
    200_NO_DEALS: You don't seem to have any active deals at the moment. Sorry, eh!
    200_NO_NEGOTIATIONS: You have no negotiations you agreeable bastard.
    200_PROPOSAL_DELETED: Proposal deleted.

    # 201 Status Code Messages
    201: Created.

    # 400 Status Code Messages
    400: Malformed request.
    400_MISSING_NEG_FIELD: At least one field must be provided for a counter-offer.
    400_EXTRA_NEG_FIELD: No negotiation field can be provided along with given response.
    400_INVALID_DATES: Start and/or end dates are invalid.
    400_BUYERS_MUST_TARGET: Buyers cannot create a proposal without targeting a publisher.
    400_BUYERS_CANNOT_SPECIFY_INVENTORY: Buyers cannot specify sections when creating a proposal or negotiating on one.
    400_SPECIFY_INVENTORY_FOR_OPEN_PROPOSAL: Publishers must specifiy inventory when creating an open proposal.

    # 401 Status Code Messages
    401: Unauthorized.
    401_INVALID_HEADER: Authentication header is invalid.
    401_NO_HEADER: Authentication header not provided.
    401_NOT_IXMUSER: 'Provided user ID is not an Index Market User. If you would like access, please contact your.mom@indexexchange.com'
    401_NOT_ACTIVE: 'Provided user ID is not currently active. If you would like access, please contact jeff.bezos@indexexchange.com'
    401_PRIVATE: 'The Index Market API is not open to the public. If you would like access, please contact larry.page@indexexchange.com'
    401_CANNOT_IMPERSONATE: You do not have permission to impersonate the provided userID.
    401_PROVIDE_IMPERSONATEID: You must provided a user ID to impersonate.

    # 403 Status Code Messages
    403: Forbidden.
    403_NOT_FORSALE: Proposal is not available for purchase.
    403_BAD_PROPOSAL: The proposal does not match the provided partner.
    
    403_PROPOSAL_IN_NEGOTIATION: Proposal is in negotiation.

    403_NEGOTIATION_BAD_PROPOSAL: The partner ID you provided does not match a partner on that proposal.
    403_NEGOTIATION_PROPOSAL_DELETED: The proposal has been deleted.
    403_NEGOTIATION_INVALID_SECTIONS: The negotiation no longer has valid sections.
    403_NEGOTIATION_NO_CHANGE: You must send a counter-offer for at least one field.
    403_NEGOTIATION_EXPIRED: The negotiation has expired.
    403_NEGOTIATION_EXISTS: A negotiation already exists on this proposal.
    403_NEGOTIATION_REJECTED_SELF: You have already rejected a negotiation on this proposal.
    403_NEGOTIATION_REJECTED_OWNER: The proposal owner has already rejected a negotiation for this proposal.
    403_NEGOTIATION_NOT_ACTIVE: This negotiation is no longer active.
    403_NEGOTIATION_PROPOSAL_BOUGHT: Proposal has already been accepted.
    403_NEGOTIATION_OTHER_REJECTED: The partner rejected this negotiation, negotiation is no longer possible. Please contact the partner directly.
    403_NEGOTIATION_OUT_OF_TURN: The partner did not reply to your previous offer.
    403_NEGOTIATION_NOT_STARTED: You cannot accept or reject a negotiation which hasn't yet started.
    403_NEGOTIATION_PARTNER_NOT_ACTIVE: The partner you have provided is no longer active.
    403_CANNOT_NEGOTIATE_OWN_PROPOSAL: You cannot start a negotiation on a proposal owned by you.
    403_CANNOT_NEGOTIATE_WITH_SAME_USERTYPE: You cannot start a negotaition with the same user type as you. 

    403_PARTNER_NOT_ACTIVE: Partner is not active
    403_PARTNER_INVALID_USERTYPE: Provided partner ID has a invalid user type.
    403_ALREADY_REJECTED: You have already rejected this negotiation, please contact the partner to continue negotiation.
    403_SECTION_NOT_OWNED: A section is not owned by the publisher part of the proposal or negotiation
    403_SECTION_NOT_ACTIVE: A section is not active.
    403_SITES_NOT_ACTIVE: All sites associated with a section are not active.

    403_CANT_ACCEPT: You cannot accept this negotiation, it is invalid.
    403_INVALID_TERMS: The negotiation terms you have provided are not valid.
    403_NO_SECTIONS: A deal cannot be created from the negotiation because there are no sections specified.

    # 404 Status Code Messages
    404: Not found.
    404_PROPOSAL_NOT_FOUND: Proposal not found.
    404_PARTNER_NOT_FOUND: Partner not found.
    404_NEGOTIATION_NOT_FOUND: Negotiation not found.
    404_SECTION_NOT_FOUND: Deal section not found.
    404_DEAL_NOT_FOUND: Deal not found.

    # 500 Status Code Messages
    500: Internal server error.