# Express Settings

# Server port
port: 8000

# Enables the "X-Powered-By: Express" HTTP header.
x-powered-by: false

# Indicates the app is behind a front-facing proxy, and to use the X-Forwarded-* headers to determine the connection and the IP address of the client.
trust proxy: false

# Specifies the default JSONP callback name.
jsonp callback name: null

# The 'replacer' argument used by `JSON.stringify`.
json replacer: null

# The 'space' argument used by `JSON.stringify`.
json spaces: 0

# Enable case sensitivity. When enabled, "/Foo" and "/foo" are different routes.
case sensitive routing: false

# Enable strict routing. When enabled, the router treats "/foo" and "/foo/" as different. Otherwise, the router treats "/foo" and "/foo/" as the same.
strict routing: false

# Enables view template compilation caching.
view cache: false

# The default engine extension to use when omitted.
view engine: null
