# Kraken Configuration

# Kraken Middleware
middleware:

    # Disable sessions.
    session:
        enabled: false

    # Security not supported without sessions.
    appsec:
        enabled: false

    # Log HTTP traffic
    logger:
        priority: 10
        module:
            name: mw:http-logger

    # Augment the express response object
    resAugmenter:
        priority: 20
        module:
            name: mw:res-augmenter

    # Handle authentication
    authHandler:
        priority: 30
        module:
            name: mw:auth-handler

    # The public access switch
    publicHandler:
        priority: 31
        module:
            name: mw:public-access-handler
    
    # Controller routes
    router:
        priority: 70
        route: /api/v1
        module:
            arguments:
                - directory: path:src/controllers

    # Handle Not Founds
    404Handler:
        priority: 99
        module:
            name: mw:404-handler

    # Middleware error handler
    errorHandler:
        priority: 100
        module:
            name: mw:error-handler



