# Kraken Configuration

# Kraken Middleware
middleware:

    # Disable sessions
    session:
        enabled: false

    # Log HTTP traffic
    logger:
        priority: 10
        module:
            name: path:./middleware/http-logger

    # Augment the express response object
    resAugmenter:
        priority: 20
        module:
            name: path:./middleware/res-augmenter

    # Handle authentication
    authHandler:
        priority: 30
        module:
            name: path:./middleware/auth-handler

    # The public access switch
    publicHandler:
        priority: 31
        module:
            name: path:./middleware/public-access-handler
    
    # Controller routes
    router:
        priority: 70
        module:
            arguments:
                - directory: path:./controllers

    # Handle Not Founds
    404Handler:
        priority: 98
        module:
            name: path:./middleware/404-handler

    # Handle Bad Request
    badRequestHandler:
        priority: 99
        module:
            name: path:./middleware/bad-request-handler

    # Middleware error handler
    errorHandler:
        priority: 100
        module:
            name: path:./middleware/error-handler



