# Logger Configuration

# Default level of messages to write to stdout.
consoleLevel: 2

# Default level of messages to write to files.
filewriteLevel: 2

# Sources of logs to override.
sourceOverrides:
    # HTTP:                   # Regex matching the name of the logger to override.
    #     consoleLevel: 3     # Console level to override.
    #     filewriteLevel: 2   # File write level to override.

    # DBMA:
    #     consoleLevel: 1
    #     filewriteLevel: 1

# Files to output JSON logs to. Relative to index.ts.
outputFiles:
    - path:logs/ixm-api-all.log

# Metadata about each level
levelMetadata:
    0:
        name: trace
        color: cyan
    1:
        name: debug
        color: green
    2:
        name: info
        color: white
    3:
        name: warn
        color: yellow
    4:
        name: error
        color: red
    5:
        name: fatal
        color: bgRed