# Logger Configuration

# Default level of messages to write to stdout.
consoleLevel: 0

# Default level of messages to write to files.
filewriteLevel: 0

# Sources of logs to override.
sourceOverrides:
    HTTP:                   # Regex matching the name of the logger to override.
        consoleLevel: 1     # Console level to override.
        filewriteLevel: 1   # File write level to override.

    DBMA:
        consoleLevel: 1
        filewriteLevel: 1

# Files to output JSON logs to. Relative to index.ts.
outputFiles:
    - path:logs/output.log

# Metadata about each level
levelMetadata:
    0:
        name: TRACE
        color: cyan
    1:
        name: DEBUG
        color: green
    2:
        name: INFO
        color: white
    3:
        name: WARN
        color: yellow
    4:
        name: ERROR
        color: red
    5:
        name: FATAL
        color: bgRed