# Logger Configuration

# Output human readable logs to stdout.
humanReadable: true

# Default level of messages to write to stdout.
consoleLevel: 2

# Default level of messages to write to files.
filewriteLevel: 2

# Sources of logs to override.
sourceOverrides:
    # HTTP:                   # Regex matching the name of the logger to override.
    #     consoleLevel: 3     # Console level to override.
    #     filewriteLevel: 2   # File write level to override.

    # DBMA:
    #     consoleLevel: 1
    #     filewriteLevel: 1

# Files to output JSON logs to. Relative to index.ts.
outputFiles:
    - path:logs/ixm-api-all.log
