# Middleware Configuration

# Log HTTP traffic
logger:
    priority: 10
    module:
        name: mw:http-logger

# Augment the express response object
response-augmenter:
    priority: 30
    module:
        name: mw:res-augmenter

# Handle authentication
authentication-handler:
    priority: 40
    module:
        name: mw:auth-handler

# JSON body parsing
json-parser:
    priority: 60
    module:
        name: body-parser
        method: json

# URL decoding request bodies
url-decoder:
    priority: 70
    module:
        name: body-parser
        method: urlencoded
        arguments:
            - extended: true

# Controller routes
router:
    priority: 90
    route: /api/v1
    module:
        name: mw:router
        arguments:
            - directory: path:src/controllers

# Handle Not Founds
404-handler:
    priority: 99
    module:
        name: mw:404-handler

# Middleware error handler
error-handler:
    priority: 100
    module:
        name: mw:error-handler

