# Validator Error Codes 

# US English
en-US:
    UNKNOWN_TYPE: 'Unknown type {{value}}.'

    ENUM_INVALID: 'Value "{{value}}" is not in [{{node.enum}}].'

    PROPERTY_MISSING: 'Missing property {{node.key}}.'
    PROPERTY_ADDITIONAL: 'Property {{value}} is forbidden.'
    
    TYPE_BOOL_INVALID: 'Value "{{value}}" is not a boolean.'

    TYPE_INT_INVALID: 'Value "{{value}}" is not an integer.'

    TYPE_NUMB_INVALID: 'Value "{{value}}" is not a number.'
    TYPE_NUMB_TOO_SMALL: 'Value "{{value}}" is too small, minimum {{node.minimum}}.'
    TYPE_NUMB_TOO_LARGE: 'Value "{{value}}" is too large, maximum {{node.maximum}}.'

    TYPE_STRING_INVALID: 'Value "{{value}}" is not a string.'
    TYPE_STRING_TOO_SHORT: 'String "{{value}}" is too short, minimum length {{node.minLength}}.'
    TYPE_STRING_TOO_LONG: 'String "{{value}}" is too long, maximum length {{node.maxLength}}.'
    TYPE_STRING_BAD_PATTERN: 'String "{{value}}" does not match {{node.pattern}}.'

    TYPE_ARRAY_INVALID: 'Value "{{value}}" is not an array.'
    TYPE_ARRAY_TOO_SHORT: 'Array does not have enough items, minimum {{node.minItems}}.'
    TYPE_ARRAY_TOO_LONG: 'Array has too many items, maximum {{node.maxItems}}.'
    TYPE_ARRAY_UNIQUE: 'Array has duplicate items.'

    TYPE_DATE_ONLY_INVALID: 'Date "{{value}}" should be of the form "yyyy-mm-dd".'

    TYPE_TIME_ONLY_INVALID: 'Time "{{value}}" should be of the form "hh:mm:ss".'

    TYPE_DATE_TIME_ONLY_INVALID: 'Date-time "{{value}}" is not a valid date-time.'

    TYPE_DATETIME_INVALID: 'Date-time "{{value}}" is not a valid date-time.'