#%RAML 1.0 

displayName: GET Deal Negotiations 204 "No Content" Reponse
description: This response will be sent if on a successful request.
value:
	code: 200
	message: Is your daddy a dealer, cause you're dope to me
	data: NegotiatedDeal[]
