#%RAML 1.0 

displayName: PUT /deals/negotiations Rejection Request
description: This request will accept the current negotation offer. If both parties have accepted, then the deal will be made live with the current negotiation terms.
value:
	proposal_id: 969
	partner_id: 696
	response: "accept"
	