 |

            This workflow illustrates a basic deal negotiation workflow between a publisher and a buyer. In this example, the buyer locates a desirable proposal, slightly amends the terms, and submits a counter-offer. The following steps are involved:

                1. List available deals,
                2. Submit a counter-offer,
                3. Respond to the counter-offer,
                4. Respond to the results,
                5. Reach an agreement.

            #### 2.2.1 List available deals

            To list all available deals, send a GET request to the `/deals/proposals` endpoint. A collection of [deal proposals]( link ) is returned.

            ```
            $ curl -X GET \
                -H 'X-Auth-ID: 1234' \
                -H 'X-Auth-Token: oFimaL5gCz9yJq2IKenrev2pclk5ul7P' \
                https://market.indexexchange.com/v1/deals/proposals
            ```

            This list may optionally be filtered by any of the available filters described in the [deal proposals route]( link ). Returned deals are limited to the pagination maximum.

            ```
            {
                "code": 200,
                "message": "Is your daddy a dealer, cause you're dope to me?"
                "data": [
                    {
                        "proposal_id": 999,
                        "owner": {
                            "owner_id": 123,
                            "contact": {
                                "title": "Captain",
                                "name": "Jimdex Exchange",
                                "email": "jimdex.exchange@indexexchange.com",
                                "phone": "666 666 6665"
                            }
                        },
                        "inventory": [4321, 9876],
                        "name": "Superfab Ultradeal",
                        "description": "DWI https://media.giphy.com/media/GODSCQebffJzW/giphy.gif",
                        "status": "active",
                        "start_date": "2017-09-09",
                        "end_date": "2017-10-10",
                        "price": 1.99,
                        "impressions": 8,
                        "budget": 9999999.99,
                        "currency": "USD",
                        "auction_type": "first",
                        "terms": "Hom ngav taq yas cha'dich 'usgheb abigaile adin billy kristina lea nomi sandra stella susana tindra choronzon corson eurynomos kali mammon mephistopheles neqa'el vapula ɔouʌɐllıs ıuʇǝƃǝɹ ɯɐƃuıs sɐƃıʇʇıs nlʇɹıɔıǝs",
                        "created_at": "2017-04-04T04:00:00Z",
                        "modified_at": "2017-04-14T14:00:00Z"
                    },
                    {
                        "proposal_id": 888,
                        "owner": {
                            "owner_id": 123,
                            "contact": "contact": {
                                "title": "Bossperson",
                                "name": "Grunt McSlab",
                                "email": "gruntslab@wemakenews4u.com",
                                "phone": "666 666 6665"
                            }
                        },
                        "inventory": [4321, 9876],
                        "name": "Superfab Ultradeal",
                        "description": "DWI https://media.giphy.com/media/GODSCQebffJzW/giphy.gif",
                        "status": "active",
                        "start_date": "2017-09-09",
                        "end_date": "2017-10-10",
                        "price": 1.99,
                        "impressions": 8,
                        "budget": 999999,
                        "currency": "USD",
                        "auction_type": "first",
                        "terms": "Hom ngav taq yas cha'dich 'usgheb abigaile adin billy kristina lea nomi sandra stella susana tindra choronzon corson eurynomos kali mammon mephistopheles neqa'el vapula ɔouʌɐllıs ıuʇǝƃǝɹ ɯɐƃuıs sɐƃıʇʇıs nlʇɹıɔıǝs",
                        "created_at": "2017-04-04T04:00:00Z",
                        "modified_at": "2017-04-14T14:00:00Z"
                    }                

                ],
                "pagination": {
                    "page": 2,
                    "limit": 250,
                    "next_page_url": "https://market.indexexchange.com/deals/proposals/?page=3&limit=250",
                    "prev_page_url": "https://market.indexexchange.com/deals/proposals/?page=1&limit=250"
                }
            }
            ```

            #### 2.2.2 Submit a counter-offer

            From the returned proposals, the buyer prefers the second one – ID 888 – but wishes to negotiate further. The buyer then amends the terms and submits a counter offer via a PUT request to `/deals/negotiation`.

            The body of this request contains a Deal Negotiation JSON object containing all fields the buyer wishes to offer a counter-proposal on. Any unadjusted fields are omitted. Note that the terms field may be used for extra information or communication:

            ```
            $ curl -X PUT \
                -H 'X-Auth-ID: 1234' \
                -H 'X-Auth-Token: oFimaL5gCz9yJq2IKenrev2pclk5ul7P' \
                -d '{ "proposal_id": 888, "partner_id": 123, "price": 1.49", "end_date": "2017-02-10", "terms": "Pending approval from the boss. How is your mother doing, by the way?" }' \
                https://market.indexexchange.com/v1/deals/negotiations
            ```

            Upon success, a Negotiated Deal object is returned, containing the proposed updates. The original proposal object is included for reference.

            ```
            {
                "code": 200,
                "message": "Is your daddy a dealer, cause you're dope to me.",
                "data": [
                    {
                        "proposal": {
                            "proposal_id": 888,
                            "owner": {
                                "owner_id": 123,
                                "contact": {
                                    "title": "Bossperson",
                                    "name": "Grunt McSlab",
                                    "email": "gruntslab@wemakenews4u.com",
                                    "phone": "666 666 6665"
                                }
                            },
                            "inventory": [4321, 9876],
                            "name": "Superfab Ultradeal",
                            "description": "DWI https://media.giphy.com/media/GODSCQebffJzW/giphy.gif",
                            "status": "active",
                            "start_date": "2017-09-09",
                            "end_date": "2017-10-10",
                            "price": 1.99,
                            "impressions": 8,
                            "budget": 999999,
                            "currency": "USD",
                            "auction_type": "first",
                            "terms": "There has been too much violence. Too much pain. But I have an honorable compromise. Just walk away. Give me your pump, the oil, the gasoline, and the whole compound, and I'll spare your lives. Just walk away and we'll give you a safe passageway in the wastelands. Just walk away and there will be an end to the horror.",
                            "created_at": "2017-04-04T04:00:00Z",
                            "modified_at": "2017-04-14T14:00:00Z"
                        },
                        "partner": {
                            "id": 123,
                            "contact": {
                                "title": "Bossperson",
                                "name": "Grunt McSlab",
                                "email": "gruntslab@wemakenews4u.com",
                                "phone": "666 666 6665"
                            },
                        },
                        "status": "waiting_on_partner",
                        "start_date": null,
                        "end_date": "2017-02-10",
                        "price": 1.49,
                        "impressions": null,
                        "budget": null,
                        "terms": "Pending approval from the boss. How is your mother doing, by the way?",
                        "created_at": "2017-04-04T04:00:00Z",
                        "modified_at": "2017-04-14T14:00:00Z"
                    }
                ]
            }
            ```

            The Negotiated Deal is now returned in a GET request to `/deals/negotiations` by our user. This may be used for reference or to check the current state of the negotiation resulting from the publisher’s response.

            #### 2.2.3 Respond to counter-offer

            At this point, the publisher has three options:

                1. Accept the counter-offer as is
                2. Reject the counter-offer
                3. Respond with a new counter-offer


            ##### Accept the  counter-offer as is

            If the publisher accepts the amended terms, they respond to the same route with a PUT request containing only the relevant IDs and a response field.
            
            ```
             $ curl -X PUT \
                -H 'X-Auth-ID: 123' \
                -H 'X-Auth-Token: oFimaL5gCz9yJq2IKenrev2pclk5ul7P' \
                -d '{ "proposal_id": 888, "partner_id": 1234, "response": "accept" }' \
                https://market.indexexchange.com/v1/deals/negotiations
            ```

            Notification is sent of the acceptance and the deal becomes active. The deal is available to bid on, pending start date if applicable, and will appear in results from the GET deals/active route.

            #### Reject the counter-offer

            If the publisher is unhappy with the amended terms but does not wish to further amend them, they may reject the counter-offer. To do this, they send a PUT request with "response": "reject” as below:
            
            ```
             $ curl -X PUT \
                -H 'X-Auth-ID: 123' \
                -H 'X-Auth-Token: oFimaL5gCz9yJq2IKenrev2pclk5ul7P' \
                -d '{ "proposal_id": 888, "partner_id": 1234, "response": "reject" }' \
                https://market.indexexchange.com/v1/deals/negotiations
            ```

            Notification of rejection is sent to the buyer. The Negotiated Deal is still available from the GET `/deals/negotiations` route, with the rejection status.

            The buyer can no longer negotiate on this deal. New proposals may still be sent to the publisher.

            #### Submit a counter-offer

            If the publisher partially accepts the terms in the counter-offer, they may amend some of the terms and submit their own counter-offer. The publisher submits this via PUT to `/deals/negotiations` in a similar fashion:

            ```
            $ curl -X PUT \
                -H 'X-Auth-ID: 123' \
                -H 'X-Auth-Token: oFimaL5gCz9yJq2IKenrev2pclk5ul7P' \
                -d '{ "proposal_id": 888, "partner_id": 1234, "price": 1.59", "end_date": "2017-12-10", "terms": "Like the extension, but floor too low, happy to reduce length to compensate. Understand re: approval. She's doing well, thanks." }' \
                https://market.indexexchange.com/v1/deals/negotiations
            ```

            The buyer will be notified of the update, and the deal remains available in the GET `/deals/negotiations` route.

            #### 2.2.4 Respond to results

            The buyer now has the same choice as the publisher: accept, reject, or respond with a new counter-offer. During a negotiation, steps 2 & 3 may continue until an agreement is reached.

            #### 2.2.5 Reach an agreement

            Negotiation ends when both parties accept or one party rejects the current state of the negotiation.

            ##### Both parties accept

            Submission of a counter-offer implies that the sender accepts the terms within their counter-offer. Upon acceptance by the other party, a deal becomes an [Active Deal]( link ) and is available for bidding. 
            
            Active deals are not available on the GET `/deals/negotiations` route but are accessible via the GET `/deals/active` route.

            ##### One party rejects

            If a counter-offer is rejected, the negotiation is considered closed. Once negotiation is closed, the deal remains accessible via the GET `/deals/negotiations` route for information purposes, but cannot be acted on further by that party.