 |

            This workflow illustrates the creation of a targeted proposal. Targeted proposals are created by a publisher or buyer and may target multiple parties. The relationship between sender and targeted parties is one-to-many: one buyer or publisher may send a proposal to one or more counterparts. Targeted proposals are only visible to targeted parties and the proposal owner. Once a targeted proposal has been completed via acceptance or rejection, it is closed.

            Our example demonstrates a buyer proposing a deal to two publishers via 4 steps:

                1. Create a targeted proposal,
                2. Receive responses from negotiation partners,
                3. Respond to the results,
                4. Reach an agreement.


            #### 2.3.1 Create a targeted proposal

            The buyer creates a proposal by sending a request to the PUT `/deals/proposals` route. The buyer targets the proposal to two specific publishers by via the `partners` values in the body.

            The buyer may additionally include [sites]( link ) and/or [sections]( link ) belonging to the publisher if they wish to propose specific placement targeting. The buyer may also leave these specifics to the publisher’s discretion. Any terms omitted from the proposal are considered open ended. 

            Contact information is sourced by default from the buyer’s account but can be overridden via inclusion of the `contact` field.

            ```
            $ curl -X PUT \
                -H 'X-Auth-ID: 1234' \
                -H 'X-Auth-Token: oFimaL5gCz9yJq2IKenrev2pclk5ul7P' \
                -d '{
                        "partners": [123, 456],
                        "inventory": [4321, 9876],
                        "name": "Superfab Ultradeal",
                        "description": "DWI https://media.giphy.com/media/GODSCQebffJzW/giphy.gif",
                        "start_date": "2017-09-09",
                        "end_date": "2017-10-10",
                        "price": 1.99,
                        "impressions": 8,
                        "budget": 999999,
                        "currency": "USD",
                        "auction_type": "first",
                        "contact": {
                            "title": "Lord",
                            "name": "Humungus",
                            "email": "ayatollah@rockandrollah.com",
                            "phone": "999 999 9998"
                        },
                        "terms": "Hom ngav taq yas cha'dich 'usgheb abigaile adin billy kristina lea nomi sandra stella susana tindra choronzon corson eurynomos kali mammon mephistopheles neqa'el vapula ɔouʌɐllıs ıuʇǝƃǝɹ ɯɐƃuıs sɐƃıʇʇıs nlʇɹıɔıǝs"
                    }' \
                https://market.indexexchange.com/api/v1/deals/proposals
            ```

            #### 2.3.2 Receive responses

            The publishers targeted in the proposal are notified and may respond to the proposal as with any negotiation - by choosing to accept, reject, or submit a counter-offer.

            All negotiation is one-to-one. Therefore, this example illustrates each publisher responding individually to the buyer. We also see the progression of two individual negotiation cycles. 

            The first publisher accepts the proposal as-is:
            
            ```
             $ curl -X PUT \
                -H 'X-Auth-ID: 123' \
                -H 'X-Auth-Token: oFimaL5gCz9yJq2IKenrev2pclk5ul7P' \
                -d '{ "proposal_id": 888, "partner_id": 1234, "response": "accept" }' \
                https://market.indexexchange.com/api/v1/deals/negotiations
            ```

            The second publisher opts to negotiate and submits a counter-offer:
            
            ```
             $ curl -X PUT \
                -H 'X-Auth-ID: 456' \
                -H 'X-Auth-Token: oFimaL5gCz9yJq2IKenrev2pclk5ul7P' \
                -d '{ "proposal_id": 888, "partner_id": 1234, "price": "2.99" "terms": "Try harder bro" }' \
                https://market.indexexchange.com/api/v1/deals/negotiations
            ```

            #### 2.3.3 Respond to the results.

            The buyer is notified of both responses. The first response results in an active deal, which is seen in the GET `/deals/active route`. 

            The second response results in a counter-offer, available in Negotiated Deals via the GET `/deals/negotiations` route. Upon review, the buyer concludes that the price is too high and decides to reject the counter-offer by sending a PUT request to `/deals/negotiations` as seen below:

            ```
             $ curl -X PUT \
                -H 'X-Auth-ID: 1234' \
                -H 'X-Auth-Token: oFimaL5gCz9yJq2IKenrev2pclk5ul7P' \
                -d '{ "proposal_id": 888, "partner_id": 456, "response": "reject" }' \
                https://market.indexexchange.com/api/v1/deals/negotiations
            ```

            #### 2.3.4 Reach an agreement

            All negotiation ends when both parties accept, or one party rejects the current negotiation state. 

            In this example, the negotiation cycle with the first publisher ended when the first publisher accepted the buyer’s proposal. 
            
            The negotiation cycle with the second publisher ended with the buyer’s rejection of the publisher’s counter-offer.
