#%RAML 1.0
---
################################
# Overview
################################

title: Index Exchange Buyer API
baseUri: https://market.indexexchange.com/api/{version}
version: v1
mediaType: application/json
documentation:
    -   title: Misc Notes
        content: |
            Lipsum generator - panipsum.com/generate/?submit=1&p=5&w=None&pl=3&q=&wl17=Klingon&wl58=Stripper+Names&wl62=Theological+Demons&wl102=Upside+Down+Lipsum


################################
# Object Definitions
################################

types:
    Contact:        !include types/contact.raml
    Deal:           !include types/deal.raml
    Response:       !include types/response.raml
    QueryPaging:    !include types/query_paging.raml

################################
# Route Definitions
################################

/deals:
    get:
        description: Retrieve packages from Index Market
        queryString: 
            type: [QueryPaging]
        responses:
            200: # 200 = "OK"
                body:
                    application/json:
                        type: Response
            400: # 400 = "Bad Request" use for malformed requests
            401: # 401 = "Unauthorized" authentication has failed or was not provided
            403: # 403 = "Forbidden" authentication successful but insufficient permissions
            418: # 418 = "I'm a teapot" return tea
            500: # 500 = "Internal Server Error" something done broke
    put:
        description: Create a new package in the IX system to be offered to one or more publishers. Publisher(s) may accept the package as offered, or create a counter-offer, or modify a previously created package in the IX system. Only available to the package creator.
        body:
            type: Deal
        responses:
            201: #201 = "Created"
    /{deal_id}:
        get:
        put:
        delete: